In [21]:
from flask import Flask, request, jsonify
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras import layers
import numpy as np
from PIL import Image
from io import BytesIO
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)


# Model and preprocessing parameters
IMAGE_SIZE = 256
# Assuming `model` is your trained Keras model


# Load your trained CNN model
model = load_model('CNNModel.keras')
#model.save('CNNModel.ipynb', save_format='tf')

# Define image preprocessing layers
resize_and_rescale = tf.keras.Sequential([
    layers.Resizing(IMAGE_SIZE, IMAGE_SIZE),
    layers.Rescaling(1./255),
])
CORS(app, resources={r"/process_image": {"origins": "http://localhost:3000"}})


# Define a route for processing images
@app.route('/process_image', methods=['POST'])

def process_image():
    # Receive the image file from the request
    file = request.files['file']
    print(file)
    # Read image file
    image = Image.open(BytesIO(file.read()))
    print(image)
    # Preprocess the image (resize and rescale)
    image = np.array(image)
    image = resize_and_rescale(image)
    
    # Expand dimensions to match expected input shape of the model
    image = np.expand_dims(image, axis=0)
    
    # Perform prediction using your model
    prediction = model.predict(image)
    print(prediction)
    # Convert prediction to JSON format and return
    return jsonify(prediction.tolist())

if __name__ == '__main__':
    try:
        app.run()
    except Exception as e:
        print("An error occurred:", e)



 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit


<FileStorage: '0a11f9e8-7357-48c2-8550-daeae59a1e76___RS_NLB 3588(1).JPG' ('image/jpeg')>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x219343F6FD0>
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 366ms/step


127.0.0.1 - - [07/May/2024 17:42:04] "POST /process_image HTTP/1.1" 200 -


[[0. 1. 0. 0.]]
<FileStorage: '0a11f9e8-7357-48c2-8550-daeae59a1e76___RS_NLB 3588(1).JPG' ('image/jpeg')>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x219345A9490>
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


127.0.0.1 - - [07/May/2024 17:43:19] "POST /process_image HTTP/1.1" 200 -


[[0. 1. 0. 0.]]
<FileStorage: '0a11f9e8-7357-48c2-8550-daeae59a1e76___RS_NLB 3588(1).JPG' ('image/jpeg')>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x219343F6710>
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


127.0.0.1 - - [07/May/2024 17:52:48] "POST /process_image HTTP/1.1" 200 -


[[0. 1. 0. 0.]]
<FileStorage: '0a62fe5a-22db-42e2-bca0-53a8dcfd8129___RS_NLB 0810(1).JPG' ('image/jpeg')>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x21935964990>
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


127.0.0.1 - - [07/May/2024 17:53:11] "POST /process_image HTTP/1.1" 200 -


[[0. 1. 0. 0.]]
<FileStorage: '0b3a35d8-25af-44ae-beed-398f591d5c1b___RS_NLB 0833.JPG' ('image/jpeg')>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x2193468E650>
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


127.0.0.1 - - [07/May/2024 17:53:19] "POST /process_image HTTP/1.1" 200 -


[[0. 1. 0. 0.]]
<FileStorage: '0a2dec45-729b-4825-b814-a73d14e8c7fe___R.S_HL 8211 copy.jpg' ('image/jpeg')>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=256x256 at 0x21934324110>
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


127.0.0.1 - - [07/May/2024 17:53:47] "POST /process_image HTTP/1.1" 200 -


[[0. 1. 0. 0.]]
